### PR TITLE
v2.2 rc

### PR DESCRIPTION
**Pull request by darrylmasson**
If a digitizer has more data ready than one BLT requests, we should request successively more and more data until the buffer is empty. This should allow us to run with a smaller `BLT_SIZE`, thus increasing performance in the bulk of reads, while still being able to clear full digitizers with fewer overall reads.

### CODE REVIEW

**Comment by darrylmasson** [comment]
Also, I'm including the introduction of compiler optimizations, because it's about that time.

**Review by petergaemers — APPROVED** [review]

**Comment by darrylmasson** [comment]
New changes include some tweaks to the logging to reduce the number of copying steps involved.

**Comment by darrylmasson** [comment]
Implemented a much more optimized algorithm for allocation escalation (ie the original point of this PR), but given the amount of extra stuff that's gotten shoehorned in we may as well call this what it actually is.

**Comment by darrylmasson** [comment]
Also included in this PR:
- Tweaked logging format to include the run number
- Overall time counter in V1724::Read, so we have an idea of when an algorithm is actually saving time.

**Pull request merged**
