### PR TITLE
Add citation badge

### PR DESCRIPTION
**Pull request by JoranAngevaare**
Add a badge that always points to the latest version of the code.

Currently, the latest version is:
- [DOI](https://doi.org/10.5281/zenodo.5882717)
New versions will appear under
- [DOI](https://doi.org/10.5281/zenodo.5882716)

### CODE REVIEW

**Review by darrylmasson — APPROVED** [review]
Nice

**Comment by JoranAngevaare** [comment]
@darrylmasson , we could consider making the authors fixed using a `.zenodo.json` if we need to reformat the names/affiliations

```json
{
    "language": "eng", 
    "title": "redax", 
    "creators": [
        {
            "affiliation": "University of Freiburg", 
            "name": "Darryl, M."
        }, 
        {..}
    ], 
    "access_right": "open", 
    "description": "DAQ with noSQL backend"
}

```

**Comment by darrylmasson** [comment]
Sure, though once again we're in the position of having ostensibly two separate packages in one repo. Redax is basically all mine, but I don't want to hide the various key contributions others have made to the dispatcher. I'm not sure what the best way is to deal with this.

**Comment by JoranAngevaare** [comment]
> Sure, though once again we're in the position of having ostensibly two separate packages in one repo. Redax is basically all mine, but I don't want to hide the various key contributions others have made to the dispatcher

don't forget the Hypervisor, although those contributions got lost in the porting from `daqnt` 😉 

> I'm not sure what the best way is to deal with this.

Neither do I, currently it just orders the authors according to the number of contributions made. We could leave it like that, I don't have a strong opinion, just wanted to point out the possibility

**Comment by darrylmasson** [comment]
Well in that case I'd suggest we add `.zenodo.json` with the half-dozen contributors across the various bits.

**Review by dipedeserena — COMMENTED** [review]
I did not know about the `zenodo.json` file but it seems a good idea also to me, thanks!

**Comment by petergaemers** [comment]
> Redax is basically all mine
@darrylmasson I'm sure no one on this list will argue anything against that

**Review by petergaemers — APPROVED** [review]

**Review by dipedeserena — APPROVED** [review]

**Comment by AlexElykov** [comment]
Looks fine to me, thanks!

**Pull request merged**
