### PR TITLE
Caches run start time

### PR DESCRIPTION
**Pull request by darrylmasson**
Because it's much more efficient than constantly hammering the RunsDB, even though it's hitting indexed fields.

### CODE REVIEW

**Comment by darrylmasson** [comment]
This fixes #38

**Review by jorana — COMMENTED** [review]
Why not use `str(number)` instead of a tuple? Looks a bit strange.

Perhaps even easier is just keeping the 10 largest run-numbers in the cache.

**Comment by darrylmasson** [comment]
I had already used a tuple first, but I agree that strings are cleaner. Keeping the largest 10 in the cache won't have the desired effect as there are at most only 3 active at once, and it's very easy for one detector to run through 10 or 15 short runs while another detector has a much longer run.

**Comment by jorana** [comment]
This is true, I don't see very quickly any potential loopholes in the logic that allow either for premature deletion or infinite cashing (oh dear, the shear memory loss involved 😉 ).

**Review by jorana — APPROVED** [review]

**Comment by darrylmasson** [comment]
In the worst case where we cache _all_ the run start times, this is at most a few MB over the entire lifetime of the experiment.

**Comment by jorana** [comment]
exactly 😉

**Pull request merged**
